// This is an autogenerated file from running `genkit init`.
'use server';
/**
 * @fileOverview A flow to optimize blog posts for SEO using AI.
 *
 * - aiSEOBlog - A function that handles the SEO optimization process.
 * - AISEOBlogInput - The input type for the aiSEOBlog function.
 * - AISEOBlogOutput - The return type for the aiSEOBlog function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AISEOBlogInputSchema = z.object({
  title: z.string().describe('The title of the blog post.'),
  content: z.string().describe('The content of the blog post in markdown format.'),
  keywords: z.string().describe('Comma separated list of keywords related to the blog post.'),
});
export type AISEOBlogInput = z.infer<typeof AISEOBlogInputSchema>;

const AISEOBlogOutputSchema = z.object({
  optimizedTitle: z.string().describe('The SEO optimized title of the blog post.'),
  optimizedContent: z.string().describe('The SEO optimized content of the blog post.'),
  metaDescription: z.string().describe('The generated meta description for the blog post.'),
});
export type AISEOBlogOutput = z.infer<typeof AISEOBlogOutputSchema>;

export async function aiSEOBlog(input: AISEOBlogInput): Promise<AISEOBlogOutput> {
  return aiSEOBlogFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiSEOBlogPrompt',
  input: {schema: AISEOBlogInputSchema},
  output: {schema: AISEOBlogOutputSchema},
  prompt: `You are an SEO expert. Optimize the following blog post for search engines.

Title: {{{title}}}
Content: {{{content}}}
Keywords: {{{keywords}}}

Instructions:
1.  Rewrite the title to be more engaging and SEO-friendly.
2.  Optimize the content for readability and keyword density.
3.  Generate a compelling meta description for the blog post.

Output the optimized title, content, and meta description.

Make sure to include the keywords naturally within the content and meta description.

Output in JSON format. Make sure it is valid. The keys should be optimizedTitle, optimizedContent, and metaDescription.
`,
});

const aiSEOBlogFlow = ai.defineFlow(
  {
    name: 'aiSEOBlogFlow',
    inputSchema: AISEOBlogInputSchema,
    outputSchema: AISEOBlogOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
